/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <ManipulationInterface.h>

#include <yarp/os/idl/WireTypes.h>

#include <algorithm>

// grasp_object helper class declaration
class ManipulationInterface_grasp_object_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_grasp_object_helper() = default;
    explicit ManipulationInterface_grasp_object_helper(const std::vector<double>& handPoses);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::vector<double>& handPoses);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::vector<double> handPoses{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::vector<double>&);
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"grasp_object"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{3};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::grasp_object(const std::vector<double>& handPoses)"};
    static constexpr const char* s_help{""};
};

// is_finished helper class declaration
class ManipulationInterface_is_finished_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_is_finished_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"is_finished"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::is_finished()"};
    static constexpr const char* s_help{""};
};

// move_object_to_pose helper class declaration
class ManipulationInterface_move_object_to_pose_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_move_object_to_pose_helper() = default;
    ManipulationInterface_move_object_to_pose_helper(const std::vector<double>& pose, const double time);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        Command(const std::vector<double>& pose, const double time);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::vector<double> pose{};
        double time{0.0};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::vector<double>&, const double);
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"move_object_to_pose"};
    static constexpr size_t s_tag_len{4};
    static constexpr size_t s_cmd_len{6};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::move_object_to_pose(const std::vector<double>& pose, const double time)"};
    static constexpr const char* s_help{""};
};

// move_hands_to_pose helper class declaration
class ManipulationInterface_move_hands_to_pose_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_move_hands_to_pose_helper() = default;
    ManipulationInterface_move_hands_to_pose_helper(const std::vector<double>& poses, const double time);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        Command(const std::vector<double>& poses, const double time);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::vector<double> poses{};
        double time{0.0};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::vector<double>&, const double);
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"move_hands_to_pose"};
    static constexpr size_t s_tag_len{4};
    static constexpr size_t s_cmd_len{6};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::move_hands_to_pose(const std::vector<double>& poses, const double time)"};
    static constexpr const char* s_help{""};
};

// move_hands_by_action helper class declaration
class ManipulationInterface_move_hands_by_action_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_move_hands_by_action_helper() = default;
    explicit ManipulationInterface_move_hands_by_action_helper(const std::string& actionName);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::string& actionName);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::string actionName{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::string&);
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"move_hands_by_action"};
    static constexpr size_t s_tag_len{4};
    static constexpr size_t s_cmd_len{5};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::move_hands_by_action(const std::string& actionName)"};
    static constexpr const char* s_help{""};
};

// move_to_configuration helper class declaration
class ManipulationInterface_move_to_configuration_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_move_to_configuration_helper() = default;
    ManipulationInterface_move_to_configuration_helper(const std::vector<double>& jointConfiguration, const double time);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        Command(const std::vector<double>& jointConfiguration, const double time);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::vector<double> jointConfiguration{};
        double time{0.0};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::vector<double>&, const double);
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"move_to_configuration"};
    static constexpr size_t s_tag_len{3};
    static constexpr size_t s_cmd_len{5};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::move_to_configuration(const std::vector<double>& jointConfiguration, const double time)"};
    static constexpr const char* s_help{""};
};

// move_to_named_configuration helper class declaration
class ManipulationInterface_move_to_named_configuration_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_move_to_named_configuration_helper() = default;
    explicit ManipulationInterface_move_to_named_configuration_helper(const std::string& configName);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::string& configName);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::string configName{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::string&);
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"move_to_named_configuration"};
    static constexpr size_t s_tag_len{4};
    static constexpr size_t s_cmd_len{5};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::move_to_named_configuration(const std::string& configName)"};
    static constexpr const char* s_help{""};
};

// release_object helper class declaration
class ManipulationInterface_release_object_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_release_object_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"release_object"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::release_object()"};
    static constexpr const char* s_help{""};
};

// stop helper class declaration
class ManipulationInterface_stop_helper :
        public yarp::os::Portable
{
public:
    ManipulationInterface_stop_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(ManipulationInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"stop"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool ManipulationInterface::stop()"};
    static constexpr const char* s_help{""};
};

// grasp_object helper class implementation
ManipulationInterface_grasp_object_helper::ManipulationInterface_grasp_object_helper(const std::vector<double>& handPoses) :
        cmd{handPoses}
{
}

bool ManipulationInterface_grasp_object_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_grasp_object_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

ManipulationInterface_grasp_object_helper::Command::Command(const std::vector<double>& handPoses) :
        handPoses{handPoses}
{
}

bool ManipulationInterface_grasp_object_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_grasp_object_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_grasp_object_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_FLOAT64, handPoses.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(handPoses.data()), handPoses.size() * sizeof(double))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_FLOAT64) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    handPoses.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(handPoses.data()), handPoses.size() * sizeof(double))) {
        return false;
    }
    reader.readListEnd();
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_grasp_object_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_grasp_object_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_grasp_object_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_grasp_object_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->grasp_object(cmd.handPoses);
}

// is_finished helper class implementation
bool ManipulationInterface_is_finished_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_is_finished_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool ManipulationInterface_is_finished_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_is_finished_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_is_finished_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_is_finished_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_is_finished_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool ManipulationInterface_is_finished_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_is_finished_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_is_finished_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_is_finished_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_is_finished_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_is_finished_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_is_finished_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_is_finished_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->is_finished();
}

// move_object_to_pose helper class implementation
ManipulationInterface_move_object_to_pose_helper::ManipulationInterface_move_object_to_pose_helper(const std::vector<double>& pose, const double time) :
        cmd{pose, time}
{
}

bool ManipulationInterface_move_object_to_pose_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_move_object_to_pose_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

ManipulationInterface_move_object_to_pose_helper::Command::Command(const std::vector<double>& pose, const double time) :
        pose{pose},
        time{time}
{
}

bool ManipulationInterface_move_object_to_pose_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_move_object_to_pose_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_move_object_to_pose_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_FLOAT64, pose.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(pose.data()), pose.size() * sizeof(double))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    if (!writer.writeFloat64(time)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_FLOAT64) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    pose.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(pose.data()), pose.size() * sizeof(double))) {
        return false;
    }
    reader.readListEnd();
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(time)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_move_object_to_pose_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_move_object_to_pose_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_move_object_to_pose_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_move_object_to_pose_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->move_object_to_pose(cmd.pose, cmd.time);
}

// move_hands_to_pose helper class implementation
ManipulationInterface_move_hands_to_pose_helper::ManipulationInterface_move_hands_to_pose_helper(const std::vector<double>& poses, const double time) :
        cmd{poses, time}
{
}

bool ManipulationInterface_move_hands_to_pose_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_move_hands_to_pose_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

ManipulationInterface_move_hands_to_pose_helper::Command::Command(const std::vector<double>& poses, const double time) :
        poses{poses},
        time{time}
{
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_FLOAT64, poses.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(poses.data()), poses.size() * sizeof(double))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    if (!writer.writeFloat64(time)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_FLOAT64) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    poses.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(poses.data()), poses.size() * sizeof(double))) {
        return false;
    }
    reader.readListEnd();
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(time)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_move_hands_to_pose_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_move_hands_to_pose_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_move_hands_to_pose_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_move_hands_to_pose_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->move_hands_to_pose(cmd.poses, cmd.time);
}

// move_hands_by_action helper class implementation
ManipulationInterface_move_hands_by_action_helper::ManipulationInterface_move_hands_by_action_helper(const std::string& actionName) :
        cmd{actionName}
{
}

bool ManipulationInterface_move_hands_by_action_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_move_hands_by_action_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

ManipulationInterface_move_hands_by_action_helper::Command::Command(const std::string& actionName) :
        actionName{actionName}
{
}

bool ManipulationInterface_move_hands_by_action_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_move_hands_by_action_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_move_hands_by_action_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(actionName)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(actionName)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_move_hands_by_action_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_move_hands_by_action_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_move_hands_by_action_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_move_hands_by_action_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->move_hands_by_action(cmd.actionName);
}

// move_to_configuration helper class implementation
ManipulationInterface_move_to_configuration_helper::ManipulationInterface_move_to_configuration_helper(const std::vector<double>& jointConfiguration, const double time) :
        cmd{jointConfiguration, time}
{
}

bool ManipulationInterface_move_to_configuration_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_move_to_configuration_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

ManipulationInterface_move_to_configuration_helper::Command::Command(const std::vector<double>& jointConfiguration, const double time) :
        jointConfiguration{jointConfiguration},
        time{time}
{
}

bool ManipulationInterface_move_to_configuration_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_move_to_configuration_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_move_to_configuration_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_FLOAT64, jointConfiguration.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(jointConfiguration.data()), jointConfiguration.size() * sizeof(double))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    if (!writer.writeFloat64(time)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_FLOAT64) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    jointConfiguration.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(jointConfiguration.data()), jointConfiguration.size() * sizeof(double))) {
        return false;
    }
    reader.readListEnd();
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(time)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_move_to_configuration_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_move_to_configuration_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_move_to_configuration_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_move_to_configuration_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->move_to_configuration(cmd.jointConfiguration, cmd.time);
}

// move_to_named_configuration helper class implementation
ManipulationInterface_move_to_named_configuration_helper::ManipulationInterface_move_to_named_configuration_helper(const std::string& configName) :
        cmd{configName}
{
}

bool ManipulationInterface_move_to_named_configuration_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_move_to_named_configuration_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

ManipulationInterface_move_to_named_configuration_helper::Command::Command(const std::string& configName) :
        configName{configName}
{
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(configName)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(configName)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_move_to_named_configuration_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_move_to_named_configuration_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_move_to_named_configuration_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_move_to_named_configuration_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->move_to_named_configuration(cmd.configName);
}

// release_object helper class implementation
bool ManipulationInterface_release_object_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_release_object_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool ManipulationInterface_release_object_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_release_object_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_release_object_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_release_object_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_release_object_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool ManipulationInterface_release_object_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_release_object_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_release_object_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_release_object_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_release_object_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_release_object_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_release_object_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_release_object_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->release_object();
}

// stop helper class implementation
bool ManipulationInterface_stop_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool ManipulationInterface_stop_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool ManipulationInterface_stop_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool ManipulationInterface_stop_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool ManipulationInterface_stop_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_stop_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_stop_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool ManipulationInterface_stop_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool ManipulationInterface_stop_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_stop_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool ManipulationInterface_stop_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool ManipulationInterface_stop_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool ManipulationInterface_stop_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool ManipulationInterface_stop_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void ManipulationInterface_stop_helper::call(ManipulationInterface* ptr)
{
    reply.return_helper = ptr->stop();
}

// Constructor
ManipulationInterface::ManipulationInterface()
{
    yarp().setOwner(*this);
}

bool ManipulationInterface::grasp_object(const std::vector<double>& handPoses)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_grasp_object_helper::s_prototype);
    }
    ManipulationInterface_grasp_object_helper helper{handPoses};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::is_finished()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_is_finished_helper::s_prototype);
    }
    ManipulationInterface_is_finished_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::move_object_to_pose(const std::vector<double>& pose, const double time)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_move_object_to_pose_helper::s_prototype);
    }
    ManipulationInterface_move_object_to_pose_helper helper{pose, time};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::move_hands_to_pose(const std::vector<double>& poses, const double time)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_move_hands_to_pose_helper::s_prototype);
    }
    ManipulationInterface_move_hands_to_pose_helper helper{poses, time};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::move_hands_by_action(const std::string& actionName)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_move_hands_by_action_helper::s_prototype);
    }
    ManipulationInterface_move_hands_by_action_helper helper{actionName};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::move_to_configuration(const std::vector<double>& jointConfiguration, const double time)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_move_to_configuration_helper::s_prototype);
    }
    ManipulationInterface_move_to_configuration_helper helper{jointConfiguration, time};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::move_to_named_configuration(const std::string& configName)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_move_to_named_configuration_helper::s_prototype);
    }
    ManipulationInterface_move_to_named_configuration_helper helper{configName};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::release_object()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_release_object_helper::s_prototype);
    }
    ManipulationInterface_release_object_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool ManipulationInterface::stop()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", ManipulationInterface_stop_helper::s_prototype);
    }
    ManipulationInterface_stop_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

// help method
std::vector<std::string> ManipulationInterface::help(const std::string& functionName)
{
    bool showAll = (functionName == "--all");
    std::vector<std::string> helpString;
    if (showAll) {
        helpString.emplace_back("*** Available commands:");
        helpString.emplace_back(ManipulationInterface_grasp_object_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_is_finished_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_move_object_to_pose_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_move_hands_to_pose_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_move_hands_by_action_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_move_to_configuration_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_move_to_named_configuration_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_release_object_helper::s_tag);
        helpString.emplace_back(ManipulationInterface_stop_helper::s_tag);
        helpString.emplace_back("help");
    } else {
        if (functionName == ManipulationInterface_grasp_object_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_grasp_object_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_is_finished_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_is_finished_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_move_object_to_pose_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_move_object_to_pose_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_move_hands_to_pose_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_move_hands_to_pose_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_move_hands_by_action_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_move_hands_by_action_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_move_to_configuration_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_move_to_configuration_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_move_to_named_configuration_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_move_to_named_configuration_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_release_object_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_release_object_helper::s_prototype);
        }
        if (functionName == ManipulationInterface_stop_helper::s_tag) {
            helpString.emplace_back(ManipulationInterface_stop_helper::s_prototype);
        }
        if (functionName == "help") {
            helpString.emplace_back("std::vector<std::string> help(const std::string& functionName = \"--all\")");
            helpString.emplace_back("Return list of available commands, or help message for a specific function");
            helpString.emplace_back("@param functionName name of command for which to get a detailed description. If none or '--all' is provided, print list of available commands");
            helpString.emplace_back("@return list of strings (one string per line)");
        }
    }
    if (helpString.empty()) {
        helpString.emplace_back("Command not found");
    }
    return helpString;
}

// read from ConnectionReader
bool ManipulationInterface::read(yarp::os::ConnectionReader& connection)
{
    constexpr size_t max_tag_len = 4;
    size_t tag_len = 1;

    yarp::os::idl::WireReader reader(connection);
    reader.expectAccept();
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }

    std::string tag = reader.readTag(1);
    bool direct = (tag == "__direct__");
    if (direct) {
        tag = reader.readTag(1);
    }
    while (tag_len <= max_tag_len && !reader.isError()) {
        if (tag == ManipulationInterface_grasp_object_helper::s_tag) {
            ManipulationInterface_grasp_object_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_is_finished_helper::s_tag) {
            ManipulationInterface_is_finished_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_move_object_to_pose_helper::s_tag) {
            ManipulationInterface_move_object_to_pose_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_move_hands_to_pose_helper::s_tag) {
            ManipulationInterface_move_hands_to_pose_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_move_hands_by_action_helper::s_tag) {
            ManipulationInterface_move_hands_by_action_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_move_to_configuration_helper::s_tag) {
            ManipulationInterface_move_to_configuration_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_move_to_named_configuration_helper::s_tag) {
            ManipulationInterface_move_to_named_configuration_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_release_object_helper::s_tag) {
            ManipulationInterface_release_object_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == ManipulationInterface_stop_helper::s_tag) {
            ManipulationInterface_stop_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == "help") {
            std::string functionName;
            if (!reader.readString(functionName)) {
                functionName = "--all";
            }
            auto help_strings = help(functionName);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(2)) {
                    return false;
                }
                if (!writer.writeTag("many", 1, 0)) {
                    return false;
                }
                if (!writer.writeListBegin(0, help_strings.size())) {
                    return false;
                }
                for (const auto& help_string : help_strings) {
                    if (!writer.writeString(help_string)) {
                        return false;
                    }
                }
                if (!writer.writeListEnd()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        std::string next_tag = reader.readTag(1);
        if (next_tag.empty()) {
            break;
        }
        tag.append("_").append(next_tag);
        tag_len = std::count(tag.begin(), tag.end(), '_') + 1;
    }
    return false;
}
