/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <eCubPerceptionInterface.h>

#include <yarp/os/idl/WireTypes.h>

#include <algorithm>

// get_poses helper class declaration
class eCubPerceptionInterface_get_poses_helper :
        public yarp::os::Portable
{
public:
    eCubPerceptionInterface_get_poses_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        std::vector<yarp::sig::Matrix> return_helper{};
    };

    using funcptr_t = std::vector<yarp::sig::Matrix> (*)();
    void call(eCubPerceptionInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"get_poses"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"std::vector<yarp::sig::Matrix> eCubPerceptionInterface::get_poses()"};
    static constexpr const char* s_help{""};
};

// get_center helper class declaration
class eCubPerceptionInterface_get_center_helper :
        public yarp::os::Portable
{
public:
    eCubPerceptionInterface_get_center_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        yarp::sig::Vector return_helper{};
    };

    using funcptr_t = yarp::sig::Vector (*)();
    void call(eCubPerceptionInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"get_center"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"yarp::sig::Vector eCubPerceptionInterface::get_center()"};
    static constexpr const char* s_help{""};
};

// get_distance helper class declaration
class eCubPerceptionInterface_get_distance_helper :
        public yarp::os::Portable
{
public:
    eCubPerceptionInterface_get_distance_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        double return_helper{0.0};
    };

    using funcptr_t = double (*)();
    void call(eCubPerceptionInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"get_distance"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"double eCubPerceptionInterface::get_distance()"};
    static constexpr const char* s_help{""};
};

// is_focused helper class declaration
class eCubPerceptionInterface_is_focused_helper :
        public yarp::os::Portable
{
public:
    eCubPerceptionInterface_is_focused_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(eCubPerceptionInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"is_focused"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool eCubPerceptionInterface::is_focused()"};
    static constexpr const char* s_help{""};
};

// get_face_position helper class declaration
class eCubPerceptionInterface_get_face_position_helper :
        public yarp::os::Portable
{
public:
    eCubPerceptionInterface_get_face_position_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        yarp::sig::Vector return_helper{};
    };

    using funcptr_t = yarp::sig::Vector (*)();
    void call(eCubPerceptionInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"get_face_position"};
    static constexpr size_t s_tag_len{3};
    static constexpr size_t s_cmd_len{3};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"yarp::sig::Vector eCubPerceptionInterface::get_face_position()"};
    static constexpr const char* s_help{""};
};

// get_action helper class declaration
class eCubPerceptionInterface_get_action_helper :
        public yarp::os::Portable
{
public:
    eCubPerceptionInterface_get_action_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        std::int16_t return_helper{0};
    };

    using funcptr_t = std::int16_t (*)();
    void call(eCubPerceptionInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"get_action"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"std::int16_t eCubPerceptionInterface::get_action()"};
    static constexpr const char* s_help{""};
};

// get_poses helper class implementation
bool eCubPerceptionInterface_get_poses_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool eCubPerceptionInterface_get_poses_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool eCubPerceptionInterface_get_poses_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool eCubPerceptionInterface_get_poses_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool eCubPerceptionInterface_get_poses_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool eCubPerceptionInterface_get_poses_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool eCubPerceptionInterface_get_poses_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeListBegin(BOTTLE_TAG_LIST, return_helper.size())) {
            return false;
        }
        for (const auto& _item : return_helper) {
            if (!writer.writeNested(_item)) {
                return false;
            }
        }
        if (!writer.writeListEnd()) {
            return false;
        }
    }
    return true;
}

bool eCubPerceptionInterface_get_poses_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_LIST) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    return_helper.resize(_csize);
    for (size_t _i = 0; _i < _csize; ++_i) {
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        if (!reader.readNested(return_helper[_i])) {
            reader.fail();
            return false;
        }
    }
    reader.readListEnd();
    return true;
}

void eCubPerceptionInterface_get_poses_helper::call(eCubPerceptionInterface* ptr)
{
    reply.return_helper = ptr->get_poses();
}

// get_center helper class implementation
bool eCubPerceptionInterface_get_center_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool eCubPerceptionInterface_get_center_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool eCubPerceptionInterface_get_center_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool eCubPerceptionInterface_get_center_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool eCubPerceptionInterface_get_center_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool eCubPerceptionInterface_get_center_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool eCubPerceptionInterface_get_center_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.write(return_helper)) {
            return false;
        }
    }
    return true;
}

bool eCubPerceptionInterface_get_center_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.read(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void eCubPerceptionInterface_get_center_helper::call(eCubPerceptionInterface* ptr)
{
    reply.return_helper = ptr->get_center();
}

// get_distance helper class implementation
bool eCubPerceptionInterface_get_distance_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool eCubPerceptionInterface_get_distance_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool eCubPerceptionInterface_get_distance_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool eCubPerceptionInterface_get_distance_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool eCubPerceptionInterface_get_distance_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool eCubPerceptionInterface_get_distance_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool eCubPerceptionInterface_get_distance_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeFloat64(return_helper)) {
            return false;
        }
    }
    return true;
}

bool eCubPerceptionInterface_get_distance_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void eCubPerceptionInterface_get_distance_helper::call(eCubPerceptionInterface* ptr)
{
    reply.return_helper = ptr->get_distance();
}

// is_focused helper class implementation
bool eCubPerceptionInterface_is_focused_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool eCubPerceptionInterface_is_focused_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool eCubPerceptionInterface_is_focused_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool eCubPerceptionInterface_is_focused_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool eCubPerceptionInterface_is_focused_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool eCubPerceptionInterface_is_focused_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool eCubPerceptionInterface_is_focused_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool eCubPerceptionInterface_is_focused_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void eCubPerceptionInterface_is_focused_helper::call(eCubPerceptionInterface* ptr)
{
    reply.return_helper = ptr->is_focused();
}

// get_face_position helper class implementation
bool eCubPerceptionInterface_get_face_position_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool eCubPerceptionInterface_get_face_position_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool eCubPerceptionInterface_get_face_position_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool eCubPerceptionInterface_get_face_position_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool eCubPerceptionInterface_get_face_position_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool eCubPerceptionInterface_get_face_position_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool eCubPerceptionInterface_get_face_position_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.write(return_helper)) {
            return false;
        }
    }
    return true;
}

bool eCubPerceptionInterface_get_face_position_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.read(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void eCubPerceptionInterface_get_face_position_helper::call(eCubPerceptionInterface* ptr)
{
    reply.return_helper = ptr->get_face_position();
}

// get_action helper class implementation
bool eCubPerceptionInterface_get_action_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool eCubPerceptionInterface_get_action_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool eCubPerceptionInterface_get_action_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool eCubPerceptionInterface_get_action_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool eCubPerceptionInterface_get_action_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool eCubPerceptionInterface_get_action_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool eCubPerceptionInterface_get_action_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeI16(return_helper)) {
            return false;
        }
    }
    return true;
}

bool eCubPerceptionInterface_get_action_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI16(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void eCubPerceptionInterface_get_action_helper::call(eCubPerceptionInterface* ptr)
{
    reply.return_helper = ptr->get_action();
}

// Constructor
eCubPerceptionInterface::eCubPerceptionInterface()
{
    yarp().setOwner(*this);
}

std::vector<yarp::sig::Matrix> eCubPerceptionInterface::get_poses()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", eCubPerceptionInterface_get_poses_helper::s_prototype);
    }
    eCubPerceptionInterface_get_poses_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : std::vector<yarp::sig::Matrix>{};
}

yarp::sig::Vector eCubPerceptionInterface::get_center()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", eCubPerceptionInterface_get_center_helper::s_prototype);
    }
    eCubPerceptionInterface_get_center_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : yarp::sig::Vector{};
}

double eCubPerceptionInterface::get_distance()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", eCubPerceptionInterface_get_distance_helper::s_prototype);
    }
    eCubPerceptionInterface_get_distance_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : double{};
}

bool eCubPerceptionInterface::is_focused()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", eCubPerceptionInterface_is_focused_helper::s_prototype);
    }
    eCubPerceptionInterface_is_focused_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

yarp::sig::Vector eCubPerceptionInterface::get_face_position()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", eCubPerceptionInterface_get_face_position_helper::s_prototype);
    }
    eCubPerceptionInterface_get_face_position_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : yarp::sig::Vector{};
}

std::int16_t eCubPerceptionInterface::get_action()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", eCubPerceptionInterface_get_action_helper::s_prototype);
    }
    eCubPerceptionInterface_get_action_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : std::int16_t{};
}

// help method
std::vector<std::string> eCubPerceptionInterface::help(const std::string& functionName)
{
    bool showAll = (functionName == "--all");
    std::vector<std::string> helpString;
    if (showAll) {
        helpString.emplace_back("*** Available commands:");
        helpString.emplace_back(eCubPerceptionInterface_get_poses_helper::s_tag);
        helpString.emplace_back(eCubPerceptionInterface_get_center_helper::s_tag);
        helpString.emplace_back(eCubPerceptionInterface_get_distance_helper::s_tag);
        helpString.emplace_back(eCubPerceptionInterface_is_focused_helper::s_tag);
        helpString.emplace_back(eCubPerceptionInterface_get_face_position_helper::s_tag);
        helpString.emplace_back(eCubPerceptionInterface_get_action_helper::s_tag);
        helpString.emplace_back("help");
    } else {
        if (functionName == eCubPerceptionInterface_get_poses_helper::s_tag) {
            helpString.emplace_back(eCubPerceptionInterface_get_poses_helper::s_prototype);
        }
        if (functionName == eCubPerceptionInterface_get_center_helper::s_tag) {
            helpString.emplace_back(eCubPerceptionInterface_get_center_helper::s_prototype);
        }
        if (functionName == eCubPerceptionInterface_get_distance_helper::s_tag) {
            helpString.emplace_back(eCubPerceptionInterface_get_distance_helper::s_prototype);
        }
        if (functionName == eCubPerceptionInterface_is_focused_helper::s_tag) {
            helpString.emplace_back(eCubPerceptionInterface_is_focused_helper::s_prototype);
        }
        if (functionName == eCubPerceptionInterface_get_face_position_helper::s_tag) {
            helpString.emplace_back(eCubPerceptionInterface_get_face_position_helper::s_prototype);
        }
        if (functionName == eCubPerceptionInterface_get_action_helper::s_tag) {
            helpString.emplace_back(eCubPerceptionInterface_get_action_helper::s_prototype);
        }
        if (functionName == "help") {
            helpString.emplace_back("std::vector<std::string> help(const std::string& functionName = \"--all\")");
            helpString.emplace_back("Return list of available commands, or help message for a specific function");
            helpString.emplace_back("@param functionName name of command for which to get a detailed description. If none or '--all' is provided, print list of available commands");
            helpString.emplace_back("@return list of strings (one string per line)");
        }
    }
    if (helpString.empty()) {
        helpString.emplace_back("Command not found");
    }
    return helpString;
}

// read from ConnectionReader
bool eCubPerceptionInterface::read(yarp::os::ConnectionReader& connection)
{
    constexpr size_t max_tag_len = 3;
    size_t tag_len = 1;

    yarp::os::idl::WireReader reader(connection);
    reader.expectAccept();
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }

    std::string tag = reader.readTag(1);
    bool direct = (tag == "__direct__");
    if (direct) {
        tag = reader.readTag(1);
    }
    while (tag_len <= max_tag_len && !reader.isError()) {
        if (tag == eCubPerceptionInterface_get_poses_helper::s_tag) {
            eCubPerceptionInterface_get_poses_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == eCubPerceptionInterface_get_center_helper::s_tag) {
            eCubPerceptionInterface_get_center_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == eCubPerceptionInterface_get_distance_helper::s_tag) {
            eCubPerceptionInterface_get_distance_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == eCubPerceptionInterface_is_focused_helper::s_tag) {
            eCubPerceptionInterface_is_focused_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == eCubPerceptionInterface_get_face_position_helper::s_tag) {
            eCubPerceptionInterface_get_face_position_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == eCubPerceptionInterface_get_action_helper::s_tag) {
            eCubPerceptionInterface_get_action_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == "help") {
            std::string functionName;
            if (!reader.readString(functionName)) {
                functionName = "--all";
            }
            auto help_strings = help(functionName);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(2)) {
                    return false;
                }
                if (!writer.writeTag("many", 1, 0)) {
                    return false;
                }
                if (!writer.writeListBegin(0, help_strings.size())) {
                    return false;
                }
                for (const auto& help_string : help_strings) {
                    if (!writer.writeString(help_string)) {
                        return false;
                    }
                }
                if (!writer.writeListEnd()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        std::string next_tag = reader.readTag(1);
        if (next_tag.empty()) {
            break;
        }
        tag.append("_").append(next_tag);
        tag_len = std::count(tag.begin(), tag.end(), '_') + 1;
    }
    return false;
}
