/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_MANIPULATIONINTERFACE_H
#define YARP_THRIFT_GENERATOR_SERVICE_MANIPULATIONINTERFACE_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

class ManipulationInterface :
        public yarp::os::Wire
{
public:
    // Constructor
    ManipulationInterface();

    virtual bool grasp_object(const std::vector<double>& handPoses);

    virtual bool is_finished();

    virtual bool move_object_to_pose(const std::vector<double>& pose, const double time);

    virtual bool move_hands_to_pose(const std::vector<double>& poses, const double time);

    virtual bool move_hands_by_action(const std::string& actionName);

    virtual bool move_to_configuration(const std::vector<double>& jointConfiguration, const double time);

    virtual bool move_to_named_configuration(const std::string& configName);

    virtual bool release_object();

<<<<<<< HEAD
    virtual std::string release(const bool block);

    virtual std::string ins();

    virtual std::string out();

    virtual std::string up();

    virtual std::string down();

    virtual std::string left();

    virtual std::string right();

    virtual std::string fore();

    virtual std::string aft();

    virtual std::string finished();

    virtual std::string egrasprlc();

    virtual std::string mgraspround();
=======
    virtual bool stop();
>>>>>>> 4e30317bec073bfd14d4546867160da931dc1c57

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_MANIPULATIONINTERFACE_H
