/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_MANIPULATIONINTERFACE_H
#define YARP_THRIFT_GENERATOR_SERVICE_MANIPULATIONINTERFACE_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

class ManipulationInterface :
        public yarp::os::Wire
{
public:
    // Constructor
    ManipulationInterface();

    virtual bool stop();

    virtual bool home(const bool block);

    virtual bool wave(const bool block);

    virtual bool shake(const bool block);

    virtual bool ready(const bool block);

    virtual bool pose_grasp(const bool block, const std::vector<double>& hand_frames);

    virtual bool grasp(const bool block);

    virtual bool release(const bool block);

    virtual bool ins();

    virtual bool out();

    virtual bool up();

    virtual bool down();

    virtual bool fore();

    virtual bool aft();

    virtual std::string finished();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_MANIPULATIONINTERFACE_H
