/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_OBJECTDETECTIONINTERFACE_H
#define YARP_THRIFT_GENERATOR_SERVICE_OBJECTDETECTIONINTERFACE_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/**
 * ****************************************************************************
 *                                                                             *
 *  Copyright (C) 2022 Fondazione Istituto Italiano di Tecnologia (IIT)        *
 *  All Rights Reserved.                                                       *
 *                                                                             *
 * ****************************************************************************
 */
class ObjectDetectionInterface :
        public yarp::os::Wire
{
public:
    // Constructor
    ObjectDetectionInterface();

    virtual std::vector<double> get_poses();

    virtual std::int16_t get_distance();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_OBJECTDETECTIONINTERFACE_H
